language: node_js
node_js:
  - 12
  - 11
  - 10

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 10
  env:
    NODE_ENV: test

branches:
  only:
    - master
    - next
    - develop

install: npm install

script:
  - npm run format
  - npm run build